const admin = [
  {
    id: 1,
    name: "inam",
    email: "inam@gmail.com",
    password: "123",
  },
  {
    id: 2,
    name: "inam",
    email: "inam12@gmail.com",
    password: "123",
  },
  {
    id: 3,
    name: "inam",
    email: "adminInam@example.com",
    password: "adminSecurePassword",
  },
];
const employees = [
  {
    name: "Ali Ahmed",
    email: "ali.@gmail.com",
    password: "231",
    tasks: [
      {
        title: "Develop Homepage",
        description: "Create the homepage using React.js and Ant Design",
        date: "2024-10-28",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: false,
        companyName: "Tech Solutions Inc.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Fix Bugs",
        description: "Resolve the reported issues in the login module",
        date: "2024-10-30",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: false,
        companyName: "Tech Solutions Inc.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 0,
          newTask: 0,
        },
      },
    ],
  },
  {
    name: "Fatima Khan",
    email: "fatima.khan@example.com",
    password: "securepass456",
    tasks: [
      {
        title: "Design Landing Page",
        description: "Create a modern landing page design using Figma",
        date: "2024-11-01",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: false,
        companyName: "Creative Labs",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Write Documentation",
        description: "Document API endpoints for the new features",
        date: "2024-11-05",
        newTask: true,
        completed: true,
        failed: true,
        active: true,
        assigned: false,
        status: false,
        companyName: "Creative Labs",
        taskCount: {
          active: 1,
          failed: 0,
          completed: 0,
          newTask: 1,
        },
      },
    ],
  },
  {
    name: "Zain Ul Abideen",
    email: "zai@gmail.com",
    password: "111",
    tasks: [
      {
        title: "Test Application",
        description: "Run test cases for the user dashboard",
        date: "2024-10-28",
        newTask: true,
        completed: false,
        failed: true,
        active: false,
        assigned: true,
        status: true,
        companyName: "Quality Assurance Corp.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Database Backup",
        description: "Ensure daily backup of all database records",
        date: "2024-10-29",
        newTask: true,
        completed: true,
        failed: true,
        active: false,
        assigned: true,
        status: false,
        companyName: "Quality Assurance Corp.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Test Application",
        description: "Run test cases for the user dashboard",
        date: "2024-10-28",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: true,
        companyName: "Quality Assurance Corp.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Database Backup",
        description: "Ensure daily backup of all database records",
        date: "2024-10-29",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: false,
        companyName: "Quality Assurance Corp.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
    ],
  },
  {
    name: "Aisha Malik",
    email: "aisha.malik@example.com",
    password: "safeandsecure123",
    tasks: [
      {
        title: "Implement Auth",
        description: "Develop user authentication with JWT",
        date: "2024-11-02",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: false,
        companyName: "SecureTech Ltd.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Set Up Server",
        description: "Deploy the application server on AWS",
        date: "2024-11-03",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: false,
        status: false,
        companyName: "SecureTech Ltd.",
        taskCount: {
          active: 1,
          failed: 0,
          completed: 0,
          newTask: 1,
        },
      },
    ],
  },
  {
    name: "Inam Ul Haq",
    email: "inam2@gmail.com",
    password: "123",
    tasks: [
      {
        title: "Optimize Performance",
        description: "Improve website loading speed and optimize images",
        date: "2024-10-29",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: true,
        companyName: "WebSolutions Co.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
      {
        title: "Social Media Integration",
        description: "Add social media sharing buttons",
        date: "2024-11-06",
        newTask: true,
        completed: false,
        failed: true,
        active: true,
        assigned: true,
        status: false,
        companyName: "WebSolutions Co.",
        taskCount: {
          active: 2,
          failed: 0,
          completed: 1,
          newTask: 0,
        },
      },
    ],
  },
];

// set the data local Storage for employees
export const setLocalStorageData = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
setLocalStorageData()
export const getLocalStorageData = () => {
  const employees = JSON.parse(localStorage.getItem("employees") || "[]");
  const admin = JSON.parse(localStorage.getItem("admin") || "[]");
  return { employees, admin };
};
